//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosterFims
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afisha
    {
        public int ID { get; set; }
        public string NameFilm { get; set; }
        public int Duration { get; set; }
        public string Description { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan Culminate { get; set; }
    }
}
