//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosterFims
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AfishaEntities : DbContext
    {
        private static AfishaEntities _context;
        public AfishaEntities()
            : base("name=AfishaEntities")
        {
        }

        public static AfishaEntities GetContext()
        {
            if (_context == null)
                _context = new AfishaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afisha> Afisha { get; set; }
        public virtual DbSet<RoleName> RoleName { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
